
ORDER_STATUS = ("PENDING", "SUCCESS", "FAILED", "CANCELLED", "EXPIRED")
ORDER_TYPE = ("ONE_TIME", "SUBSCRIPTION")
PAYMENT_STATUS = ("PENDING", "SUCCESS", "FAILED", "USER_DROPPED", "CANCELLED", "REFUNDED")
PAYMENT_METHOD = ("UPI", "CARD", "NETBANKING", "WALLET")
