"""add user_input_item to translated_analysis_report

Revision ID: 20260205_add_user_input_item
Revises: 20260205_152714_rename_name_hn_to_name_hi
Create Date: 2026-02-05 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260205_add_user_input_item'
down_revision = 'rename_hn_to_hi'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translated_analysis_report', sa.Column('user_input_item', sa.String(length=255), nullable=True), schema='kissan_cv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translated_analysis_report', 'user_input_item', schema='kissan_cv')
    # ### end Alembic commands ###
