"""add_status_column_to_reports_v2

Revision ID: 6d0694028d22
Revises: drop_async_jobs_table
Create Date: 2026-01-16 14:45:41.942941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d0694028d22'
down_revision: Union[str, None] = 'drop_async_jobs_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_analysis_report', sa.Column('status', sa.String(length=50), nullable=True), schema='kissan_cv')
    op.add_column('fruit_analysis_report', sa.Column('status', sa.String(length=50), nullable=True), schema='kissan_cv')
    op.add_column('vegetable_analysis_report', sa.Column('status', sa.String(length=50), nullable=True), schema='kissan_cv')
    op.add_column('translated_analysis_report', sa.Column('status', sa.String(length=50), nullable=True), schema='kissan_cv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translated_analysis_report', 'status', schema='kissan_cv')
    op.drop_column('vegetable_analysis_report', 'status', schema='kissan_cv')
    op.drop_column('fruit_analysis_report', 'status', schema='kissan_cv')
    op.drop_column('crop_analysis_report', 'status', schema='kissan_cv')
    # ### end Alembic commands ###
