"""Add Fruit and Vegetable Analysis tables

Revision ID: 836ccc321daf
Revises: 001_initial
Create Date: 2025-12-30 08:50:55.480631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '836ccc321daf'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipped SharedBackend tables
    pass
    op.create_table('fruit_analysis_report',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('fruit_name', sa.String(length=255), nullable=True),
    sa.Column('disease_name', sa.String(length=255), nullable=True),
    sa.Column('pathogen_scientific_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('analysis_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('bbox_image_url', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='kissan_cv'
    )
    op.create_index(op.f('ix_kissan_cv_fruit_analysis_report_user_id'), 'fruit_analysis_report', ['user_id'], unique=False, schema='kissan_cv')
    op.create_table('vegetable_analysis_report',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('vegetable_name', sa.String(length=255), nullable=True),
    sa.Column('disease_name', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('analysis_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('bbox_image_url', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='kissan_cv'
    )
    op.create_index(op.f('ix_kissan_cv_vegetable_analysis_report_user_id'), 'vegetable_analysis_report', ['user_id'], unique=False, schema='kissan_cv')
    # Skipped scopes tables
    pass
    # Skipped index modifications for crop
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kissan_cv_crop_analysis_report_user_id'), table_name='crop_analysis_report', schema='kissan_cv')
    op.create_index(op.f('idx_crop_analysis_report_user_id'), 'crop_analysis_report', ['user_id'], unique=False)
    op.create_index(op.f('idx_crop_analysis_report_created_at'), 'crop_analysis_report', ['created_at'], unique=False)
    op.drop_table('api_key_scopes')
    op.drop_table('scopes')
    op.drop_index(op.f('ix_kissan_cv_vegetable_analysis_report_user_id'), table_name='vegetable_analysis_report', schema='kissan_cv')
    op.drop_table('vegetable_analysis_report', schema='kissan_cv')
    op.drop_index(op.f('ix_kissan_cv_fruit_analysis_report_user_id'), table_name='fruit_analysis_report', schema='kissan_cv')
    op.drop_table('fruit_analysis_report', schema='kissan_cv')
    op.drop_table('entities')
    op.drop_table('api_keys')
    op.drop_table('aes256_encryption_keys')
    # ### end Alembic commands ###
