"""Add reasoning column to FruitAnalysis

Revision ID: a43552fd5dae
Revises: 836ccc321daf
Create Date: 2025-12-30 09:04:50.896533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43552fd5dae'
down_revision: Union[str, None] = '836ccc321daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
