"""Add language column

Revision ID: cf1a7ac1336f
Revises: 52ae3ab815aa
Create Date: 2026-01-02 22:08:24.446071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf1a7ac1336f'
down_revision: Union[str, None] = '52ae3ab815aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fruit_analysis_report', sa.Column('language', sa.String(length=10), nullable=True), schema='kissan_cv')
    op.add_column('vegetable_analysis_report', sa.Column('language', sa.String(length=10), nullable=True), schema='kissan_cv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vegetable_analysis_report', 'language', schema='kissan_cv')
    op.drop_column('fruit_analysis_report', 'language', schema='kissan_cv')
    # ### end Alembic commands ###
